
name: "\U0001F680 Feature request"
Control + shift + m: tab esc then tab"\U0001F680 Feature request"
description: Suggest an idea for this project
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an idea to improve this Bitnami Vulnerability Database.
        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Title
      description: Title of the feature request
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
      description: Describe the requests. If you already have something in mind... PRs are welcome!
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
